version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: getir_db
      POSTGRES_USER: omeraydin
      POSTGRES_PASSWORD: postgrespw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: getir-project
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/getir_db
      SPRING_DATASOURCE_USERNAME: omeraydin
      SPRING_DATASOURCE_PASSWORD: postgrespw
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data:
