spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/getir_db
    username: omeraydin
    password: postgrespw
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
jwt:
  secret: 753825833596c73052d101c78156f41575c4e7257f2147688542ffe506a9d69e
